version: "3.9"
services:
  db:
    image: postgres:16
    container_name: n8n-DB
    hostname: n8n-db
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "n8n", "-U", "n8nuserdb"]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - landb
    user: "999:999"
    volumes:
      - /sata/dk/n8n/db:/var/lib/postgresql/data:rw
    environment:
      TZ: Europe/Paris
      POSTGRES_DB: n8n
      POSTGRES_USER: n8nuserdb
      POSTGRES_PASSWORD: MonSuperMotDePasseDeLaMortQuiTue_24db!
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:1.89.2
    container_name: n8n
    hostname: n8n
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    networks:
      - lanext
      - landb
    ports:
      - "5678:5678"
    volumes:
      - /sata/dk/n8n/data:/home/node/.n8n:rw
      - /sata/dk/n8n/files:/files:rw
    environment:
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: user_n8n
      N8N_BASIC_AUTH_PASSWORD: MonSuperMotDePasseDeLaMortQuiTue_24!
      N8N_HOST: n8n.noocode.io
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      NODE_ENV: production
      WEBHOOK_URL: https://n8n.noocode.io
      N8N_EDITOR_BASE_URL: https://n8n.noocode.io
      GENERIC_TIMEZONE: Europe/Paris
      TZ: Europe/Paris
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_HOST: n8n-db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: n8nuserdb
      DB_POSTGRESDB_PASSWORD: MonSuperMotDePasseDeLaMortQuiTue_24db!
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
        
networks:
  landb:
  lanext:
    external: true